import { Button, VerticalBox, TextEdit, HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 720px;
    height: 240px;
    title: "Universal Converter";
    in-out property <string> ascii_text;
    in-out property <string> base64_text;
    callback convert_text(string);
    VerticalBox {
        HorizontalBox {
            Text {
                max-height: 60px;
                max-width: 100px;
                text: "ASCII Text";
                font-size: 20px;
                vertical-alignment: TextVerticalAlignment.center;
            }

            TextInput {
                input-type: text;
                max-height: 60px;
                text <=> root.ascii_text;
                enabled: true;
                horizontal-alignment: TextHorizontalAlignment.left;
                font-size: 20px;
                vertical-alignment: TextVerticalAlignment.center;
                selection-background-color: grey;
            }
        }

        HorizontalBox {
            Text {
                max-height: 60px;
                max-width: 100px;
                text: "Base64";
                font-size: 20px;
                vertical-alignment: TextVerticalAlignment.center;
            }

            TextEdit {
                max-height: 60px;
                text: base64_text;
                enabled: true;
                horizontal-alignment: TextHorizontalAlignment.left;
                font-size: 20px;
                accessible-label: "Base64";

            }
        }

        HorizontalBox {
            alignment: LayoutAlignment.center;
            Button {
                colorize-icon: true;
                enabled: true;
                primary: true;
                text: "Translate";
                visible: true;
                width: 100px;
                clicked => {
                    root.convert_text(root.ascii_text)
                }
            }
        }
    }
}
